name: Move to gh pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  move-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create new branch
        run: |
          git checkout -b gh-pages

      - name: Move folder
        run: |
          mkdir -p temp-folder
          mv web/* temp-folder/
          rm -rf web
          mkdir web
          mv temp-folder/* web/
          rmdir temp-folder

      - name: Commit changes
        run: |
          git add .
          git commit -m "Move web content to new branch"

      - name: Push new branch
        run: |
          git push origin gh-pages