name: Move to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  move-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: List files for debug
        run: ls -R
        
      - name: Create gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf . || true

      - name: Copy web folder contents
        run: |
          cp -r web/* .

      - name: Commit changes
        run: |
          git add .
          git commit -m "Move web content to gh-pages branch"

      - name: Push gh-pages branch
        run: |
          git push origin gh-pages --force
